version: "3.9"
services:
  api:
    build:
      context: ./src
      dockerfile: Yield.Tracker.Api/Dockerfile
    container_name: sqia-api
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=investimentos;Username=sqia;Password=sqia123
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16
    container_name: sqia-db
    restart: always
    environment:
      POSTGRES_DB: investimentos
      POSTGRES_USER: sqia
      POSTGRES_PASSWORD: sqia123
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sqia"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
